# MIT License
#
# Copyright (c) 2024 Nathanael Gandhi
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

ARG BASE_IMAGE=containers-ros2-base-image:latest
FROM ${BASE_IMAGE}
# Note: ENV ROS_DISTRO is set in BASE_IMAGE
LABEL ROS_DISTRO=${ROS_DISTRO}

################################################################################
# Ensures there is a non-root user
ARG USERNAME=builder
ARG USER_UID=1000
ARG USER_GID=$USER_UID

## Create the user
RUN if [ "$(id -un)" != "$USERNAME" ] ; then \
    groupadd --gid $USER_GID $USERNAME && \
    useradd --shell /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME && \
    echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME && \
    chmod 0440 /etc/sudoers.d/$USERNAME; \
    fi
USER $USERNAME

################################################################################
# Install basic apt packages
## editors: vim, nano
## utils-core: git ...
## utils-n2h: tree ...
RUN if [ -z "$(find /var/lib/apt/lists/ -mindepth 1 -maxdepth 1)" ]; then \
        sudo apt-get update; \
    else \
        echo "Using previous apt lists from last update"; \
    fi && \
    sudo apt-get install -y \
    vim nano \
    git ssh curl \
    tree file htop \
    direnv

################################################################################
# Ensures extend bash shell
## Oh-My-Bash extensions
RUN if [ -d ~/.oh-my-bash ]; then \
    echo "Directory ~/.oh-my-bash already exists. Not installing"; \
else \
    echo "Downloading oh-my-bash" && \
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)" --unattended && \
    sed -i 's/OSH_THEME="font"/OSH_THEME="vscode"/g' ~/.bashrc && \
    if [ $? -eq 0 ]; then \
        echo "Oh My Bash installed and theme modified"; \
    fi; \
fi

## Hook direnv
RUN if [ ! grep -q "eval \"\$(direnv hook bash)\"" ~/.bashrc ] ; then \
    echo 'eval "$(direnv hook bash)"' >> ~/.bashrc; \
fi

################################################################################
# DEVELOPER SOFTWARE - Add new additions below
################################################################################
# Install pip packages
## clang-format from apt is very old (~v14) vs pip v18+
RUN pip install \
    pdm \
    pre-commit

################################################################################
## Install ros apt packages: ros-${ROS_DISTRO}-*
## note: use individual RUN commands to allow for caching

### rqt and its plugins
# RUN sudo apt-get install -y ros-${ROS_DISTRO}-rqt-action
# RUN sudo apt-get install -y ros-${ROS_DISTRO}-rqt-common-plugins
# RUN sudo apt-get install -y ros-${ROS_DISTRO}-rqt-console
RUN sudo apt-get install -y ros-${ROS_DISTRO}-rqt-graph
RUN sudo apt-get install -y ros-${ROS_DISTRO}-rqt-publisher
# RUN sudo apt-get install -y ros-${ROS_DISTRO}-rqt-reconfigure
# RUN sudo apt-get install -y ros-${ROS_DISTRO}-rqt-service-caller
# RUN sudo apt-get install -y ros-${ROS_DISTRO}-rqt-srv
# RUN sudo apt-get install -y ros-${ROS_DISTRO}-rqt-topic
# RUN sudo apt-get install -y ros-${ROS_DISTRO}-rqt*

### rviz2
# RUN sudo apt-get install -y ros-${ROS_DISTRO}-rviz2

### gazebo & ros_gz
# RUN sudo apt-get install -y ros-${ROS_DISTRO}-ros-gz

################################################################################
ENTRYPOINT ["/bin/bash"]
